ServiceWebsite/ServiceWebsite/ClientApp/src/translate/messages.xlf

N/A
Generated translation resource file for the contents that is already in the master
```
[ ] Yes
[ x] No
```

Regenerated translation file

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/audio-bar/audio-bar.component.ts

resume audio context to make green audio bar moving
```
[ ] Yes
[ X] No
```

resume audioContext, fix green audio bar

---

ServiceWebsite/ServiceWebsite/ClientApp/src/translate/messages.xlf

N/A
Updated translation file
```
[ ] Yes
[ x] No
```

Updated translation file

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/user-camera-view/user-camera-view.component.ts

https://tools.hmcts.net/jira/browse/VIH-4498
fix audio for participant-view, illuminated sound interference by muted the sound on self-view video
```
[ ] Yes
[x ] No
```

fix audio sound -4498

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/CommonPages.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/AboutHearings.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/DifferentHearingTypes.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/MediaError.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/ParticipantView.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/UseCameraMicrophone.cs

N/A
Removed text validation on pages
```
[ ] Yes
[x] No
```

removed content validation

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/PageUri.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/AboutHearings.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/CourtBuildingVideo.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/DifferentHearingTypes.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/ExploreCourtBuilding.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/HelpTheCourtDecide.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/ParticipantView.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/UseCameraMicrophone.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs

N/A
Doing some house cleaning
```
[] Yes
[x] No
```

Tidy up codes

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/IndividualInformationVideo.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/IndividualInformationVideo.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/PageUri.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/SeleniumEnvironment.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/AboutYou.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/CourtBuildingVideo.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/ExploreCourtBuilding.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/MediaError.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/ParticipantView.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/AboutYouSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/BlueInformationScreensSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/InformationVideoSteps.cs

https://tools.hmcts.net/jira/browse/VIH-4399
https://tools.hmcts.net/jira/browse/VIH-4403
Acceptance tests to cover individual journey to About You page
```
[ ] Yes
[x] No
```

Individual Proceeds to About You page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/different-hearing-types/different-hearing-types.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/header/header.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.scss
ServiceWebsite/ServiceWebsite/ClientApp/src/translate/messages.xlf

https://tools.hmcts.net/jira/browse/VIH-4493
Fixed Logout button issue in Mobile View
```
[ ] Yes
[X ] No
```

Fixed Logout button issue

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.html

https://tools.hmcts.net/jira/browse/VIH-4509
Fix to show correct error message on Edge when Video is Unavailable 
```
[ ] Yes
[X ] No
```

Fixed issue in Edge

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-video-hearing/explore-video-hearing.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/translate/messages.xlf

https://tools.hmcts.net/jira/browse/VIH-4400
Changes to the text for hearding and description
```
[ ] Yes
[ x] No
```

VIH-4400 - Text changes to the heading and description

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/IndividualPages/UseCameraMicrophone.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/use-camera-microphone/use-camera-microphone.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/translate/messages.xlf

https://tools.hmcts.net/jira/browse/VIH-4508
Remove 'microphone' words
```
[ ] Yes
[X ] No
```

Change wording, remove microphone

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/help-the-court-decide/help-the-court-decide.component.html

https://tools.hmcts.net/jira/browse/VIH-4512
Text changes on HelpTheCourtDecide page
```
[ ] Yes
[X ] No
```

Text changes on HelpTheCourtDecide page

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs

https://tools.hmcts.net/jira/browse/VIH-3937
Acceptance test for individual to view information video - court hearings
```
[ ] Yes
[x] No
```

Court building video

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/interpreter/interpreter.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/show-details/show-details.component.html

https://tools.hmcts.net/jira/browse/VIH-4333
Individual Interpreter question changes
```
[ ] Yes
[ X] No
```

Individual Interpreter question changes

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-your-computer/about-your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.html

https://tools.hmcts.net/jira/browse/VIH-4523
Change button value
```
[ ] Yes
[X ] No
```

change button value re-play the video

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-you/about-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-your-computer/about-your-computer.component.html

Fix layout of the page about-your-computer
```
[ ] Yes
[ X] No
```

Fix layout of the page about-your-computer

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.ts

https://tools.hmcts.net/jira/browse/VIH-4539
Stop playing first video after navigation to another page
```
[ ] Yes
[X ] No
```

reset video source to null on destroy

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.ts

https://tools.hmcts.net/jira/browse/VIH-4336
Changes related to "Your Internet Connection" question for Individual
```
[ ] Yes
[X ] No
```

Vih 4336 your internet connection

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/YourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/PageUri.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/DecisionJourney.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/IndividualQuestionnaireJourney.cs

https://tools.hmcts.net/jira/browse/VIH-4335
Acceptance tests to ask if individual computer has got both camera and microphone.
```
[ ] Yes
[x] No
```

Acceptance test - about you computer

---

ServiceWebsite/ServiceWebsite/ClientApp/package-lock.json
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/login/login.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/login/login.component.ts
ServiceWebsite/ServiceWebsite/Properties/launchSettings.json

https://tools.hmcts.net/jira/browse/VIH-4501
Changed the login component to not add the return url if it is the same as the current path
```
[ ] Yes
[x ] No
```

VIH-4501 login first time gets stuck on logging in page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/logout/logout.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/header/header.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/header/header.component.html

https://tools.hmcts.net/jira/browse/VIH-4528
Title styling changes
```
[ ] Yes
[X ] No
```

Fix related to mobile header

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYou.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYou.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AccessToRoom.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AccessToRoom.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/InternetConnection.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/InternetConnection.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Interpreter.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Interpreter.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/YourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/AnswerType.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/PageUri.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/IndividualQuestionnaireJourney.cs

https://tools.hmcts.net/jira/browse/VIH-4337
Acceptance tests for court to know whether participant will have access to a suitable room or not.
```
[ ] Yes
[x] No
```

Acceptance test - access to a room page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/logout/logout.component.ts

https://tools.hmcts.net/jira/browse/VIH-4503
Fix for login link
```
[ ] Yes
[ X] No
```

Login link issue

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view-base/video-view-base.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey-steps.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-steps-order.factory.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-steps-order.factory.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/access-to-room/access-to-room.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-court-building/explore-court-building.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-video-hearing/explore-video-hearing.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-video-hearing/explore-video-hearing.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-video-hearing/explore-video-hearing.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/individual-base-component/component-test-bed.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-component-bindings.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-routing-listener.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-routing-listener.service.ts

https://tools.hmcts.net/jira/browse/VIH-4111
Changes for journey for mobile device
```
[ X] Yes
[ ] No
```

Journey for individual mobile device

---

ServiceWebsite/ServiceWebsite/ClientApp/package-lock.json
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/hearing-details-header/hearing-details-header.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/hearing-details-header/hearing-details-header.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/hearing-details-header/hearing-details-header.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/hearing-details-header/hearing-details-header.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-you/about-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/representative-base-component/component-test-bed.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.module.ts

https://tools.hmcts.net/jira/browse/VIH-4430
Added in a stub for the hearing info header so that it can be reused in other stories. Styling is a little bit off and it is completely static now, I will fix these things later.
```
[ ] Yes
[X] No
```

Added in a stub header component

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey-steps.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-steps-order.factory.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/services/representative-journey-component-bindings.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/services/representative-journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/services/representative-journey-routing-listener.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/services/representative-journey-routing-listener.service.ts

https://tools.hmcts.net/jira/browse/VIH-4290
Refactored Representative Steps. Replaced  Enum with the class and Instances for Reusability
```
[ ] Yes
[X ] No
```

Feature/vih 4290 refactor steps - Representative Steps

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-hearings/about-hearings.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/different-hearing-types/different-hearing-types.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-you-and-your-client/about-you-and-your-client.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/crest-blue-panel/crest-blue-panel.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.css
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.scss

https://tools.hmcts.net/jira/browse/VIH-4429
This PR contains the following
- Added html for the About you and your client blue screen.
- Removed the contact us component from blue crest component.
- Added the contact us component to the first 2 blue screens in individual journey.
```
[ ] Yes
[x] No
```

VIH-4429-Representative views Blue Screen 2

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/suitability-choice-page-base.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/suitability-choice-page-base.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/suitability-choice-page-base.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/suitability-choice-page-base.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/individual-base-component/component-test-bed.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/components/suitability-choice-page-base.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/components/suitability-choice-page-base.component.ts

https://tools.hmcts.net/jira/browse/VIH-4430
Managed to create different base classes for the choice button pages base component.
It's still not perfect but it will allow us to reuse most of the functionality of the choice base component. Also, it doesn't break any existing components.
In order to not have to update all the usages, I refrained from renaming the `SuitabilityChoiceBaseComponent` to `IndividualSuitabilityBaseComponent`. I'll do this in the next step though because it makes less sense.
```
[ ] Yes
[X] No
```

Vih 4430 choice base component

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/thank-you/thank-you.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/thank-you/thank-you.component.ts

https://tools.hmcts.net/jira/browse/VIH-4444
small modification for Thank you page
```
[ ] Yes
[ x] No
```

amended Thank you page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/please-contact-us/please-contact-us.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/please-contact-us/please-contact-us.component.ts

https://tools.hmcts.net/jira/browse/VIH-4563
Amended the code to remove un-used imports.
```
[ ] Yes
[x] No
```

amended code, removed un-used imports

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/access-to-room/access-to-room.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/access-to-room/access-to-room.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-computer/your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-computer/your-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-computer/your-computer.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.css

https://tools.hmcts.net/jira/browse/VIH-4433
This PR contains the component and html for the 'Your computer' representative journey.
```
[ ] Yes
[x] No
```

Added 'Your Computer' page for Rep journey

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/access-to-room/access-to-room.component.html

https://tools.hmcts.net/jira/browse/VIH-4432
Added '?' mark to text points
```
[ ] Yes
[ X] No
```

Add ? mark

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-your-computer/about-your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-your-computer/about-your-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-your-computer/about-your-computer.component.ts

https://tools.hmcts.net/jira/browse/VIH-4434
Page 'about your computer' for representative 
```
[ X] Yes
[ ] No
```

about you computer for rep

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/YourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/YourComputer.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/RepresentativeQuestionnaireSteps.cs

https://tools.hmcts.net/jira/browse/VIH-4433
Acceptance test for Representative's 'Your computer' question
```
[ ] Yes
[x ] No
```

Vih 4433 your computer rep

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/RepresentativeQuestionnaireSteps.cs

https://tools.hmcts.net/jira/browse/VIH-4434
Acceptance test for Representative's 'About Your computer' question
```
[ ] Yes
[ x] No
```

Vih 4434 about your computer rep

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-you/about-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-you/about-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/about-your-client/about-your-client.component.html

https://tools.hmcts.net/jira/browse/VIH-4598
This PR contains ahtml fix for the accessibility issue.
updated the about you and consent pages.
```
[ ] Yes
[x] No
```

updated html for accessibility error

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/footer/footer.component.html

https://tools.hmcts.net/jira/browse/VIH-4630
The PR contains an update to the feedback url.
```
[ ] Yes
[x] No
```

updated the feedback url

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/thank-you/thank-you.component.html

https://tools.hmcts.net/jira/browse/VIH-4631
This PR contains an update to the feedback link
```
[ ] Yes
[x] No
```

updated feedback link

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourClient.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/HearingSuitability.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/HearingSuitability.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/RepresentativeQuestionnaireSteps.cs

https://tools.hmcts.net/jira/browse/VIH-4442
Acceptance test for Representative's 'hearing suitability' journey
```
[ ] Yes
[ x] No
```

Vih 4442 hearing suitability

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.html

https://tools.hmcts.net/jira/browse/VIH-4443
```
[ ] Yes
[ x] No
```

VIH-4443: Fix image location when deployed

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/suitability.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/suitability.service.ts

https://tools.hmcts.net/jira/browse/VIH-4640
Service that calls suitability api to save answers
```
[ ] Yes
[ x] No
```

Service that calls suitability api to save answers

---

CODEOWNERS

n/a
Added @rehmanab to codeowners.
```
[ ] Yes
[X] No
```

Added atif to codeowners

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.ts

https://tools.hmcts.net/jira/browse/VIH-4641
stubbed a submit method, which sets the isSubmitted flag to true. 
```
[ ] Yes
[x] No
```

added submit flag

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/participant-model-mapper.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/individual-model-mapper.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/individual-model-mapper.ts

Sub Task : https://tools.hmcts.net/jira/browse/VIH-4639
Main ticket : https://tools.hmcts.net/jira/browse/VIH-4567
Mapper to Map Suitability Model into the Submit Request
```
[ ] Yes
[ x] No
```

WIP Vih 4639 mapper to suitability request

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.ts

https://tools.hmcts.net/jira/browse/VIH-4653
Added missing question on Questionaire completed page
```
[ ] Yes
[X ] No
```

Bug Fix missing Question 

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AccessToRoom.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AccessToRoom.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/QuestionnaireCompleted.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/QuestionnaireCompleted.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/RepresentativeQuestionnaireSteps.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.html

https://tools.hmcts.net/jira/browse/VIH-4443
- Added more tests to cover negative scenarios for questionnaire completed page
- Also checks for presence of print link
```
[ ] Yes
[ x] No
```

Added more tests to cover negative scenarios

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/print.service.ts

https://tools.hmcts.net/jira/browse/VIH-4650
Fix for Print issue on Firefox
```
[ ] Yes
[ X] No
```

Fix for Print issue on Firefox

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Consent.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Consent.feature.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/IndividualQuestionnaireSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/QuestionnaireJourney.cs

n/a
Fixed failing test in AAT on consent page
```
[ ] Yes
[ x] No
```

Fixed failing test in AAT

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.ts

https://tools.hmcts.net/jira/browse/VIH-4568
Changes related to redirecting to Video App if answers already submitted for one of the hearing
```
[ ] Yes
[X ] No
```

Redirect to Video App Answers already Submitted

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/see-and-hear-video/see-and-hear-video.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/see-and-hear-video/see-and-hear-video.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/see-and-hear-video/see-and-hear-video.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/paths.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-journey-routing.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-journey-steps.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-steps-order.factory.ts

https://tools.hmcts.net/jira/browse/VIH-4578
Added missing pages
```
[ ] Yes
[ x] No
```

VIH-4577: Adding last few pages

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/journey-base.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.factory.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-steps-order.factory.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-component-bindings.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/same-computer/same-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/same-computer/same-computer.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/see-and-hear-video/see-and-hear-video.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/see-and-hear-video/see-and-hear-video.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/use-camera-microphone-again/use-camera-microphone-again.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/use-camera-microphone-again/use-camera-microphone-again.component.ts

https://tools.hmcts.net/jira/browse/VIH-4577
Added in self-test journey for the individual.
Missing acceptance tests that will have to be amended, also some of the code is tightly linked now which can be improved but it shows the gist.
It builds on the PR for moving journey transition into the components: https://github.com/hmcts/vh-service-web/pull/222
```
[X] Yes
[ ] No
```

Refactored journey self test

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/sign-in-other-computer/sign-in-other-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/sign-in-other-computer/sign-in-other-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/sign-in-other-computer/sign-in-other-computer.component.ts

https://tools.hmcts.net/jira/browse/VIH-4577
I removed journey dependency from this component since you can't "next" or continue from it. It's a dead end.
```
[ ] Yes
[X] No
```

Removed superfluous code from sign-back-in component

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.ts

https://tools.hmcts.net/jira/browse/VIH-4577
(1) Added equipment check buttons on "Camera Working" and "Microphone Working" pages
```
[ ] Yes
[ X] No
```

Added Equipment Check buttons

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/same-computer/same-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/same-computer/same-computer.component.ts

https://tools.hmcts.net/jira/browse/VIH-4578
Changed related to Navigating to SignInOtherComputer When device logged is mobile or Answer is no for same computer
```
[ ] Yes
[ X] No
```

Changed Navigation and Tests

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/participant-suitability.model.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/participant-suitability.model.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/individual-base-component/individual-component-test-bed.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-journey-steps.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/logger.spec.ts

https://tools.hmcts.net/jira/browse/VIH-4577
Make the representative re-enter at self-test when questionnaire have been submitted.
```
[X] Yes
[ ] No
```

Re-enter at self-test after submitting questionnaire

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/logout/logout.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/logout/logout.component.ts

https://tools.hmcts.net/jira/browse/VIH-4578
Clear session storage
```
[ ] Yes
[ x] No
```

VIH-4578: Clear session storage

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Constants/RepresentativeQuestionKeys.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Contexts/TestContext.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/QuestionnaireCompleted.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataSetUp.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/RepresentativeQuestionnaireSteps.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.html

n/a
Added extra logic to verify the data stored in the database
```
[ ] Yes
[ x] No
```

Updated questionnaire test to verify the data stored in the database

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/switch-on-camera-and-microphone/switch-on-camera-and-microphone.component.html

https://tools.hmcts.net/jira/browse/VIH-4068
Fixed Styling Issues
```
[ ] Yes
[ ] No
```

VIH- 4068 -Fixed Styling Issue

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-3942
change .yml file added variables for pexip node, custom token for pexip, and VhServiceResourceId
```
[ ] Yes
[ X] No
```

add variables to pipeline .yml

---

azure-pipelines.yml

n/a
adding missing build triggers.
```
[ ] Yes
[x ] No
```

New build triggers

---

ServiceWebsite/ServiceWebsite/ClientApp/angular.json
ServiceWebsite/ServiceWebsite/ClientApp/package-lock.json
ServiceWebsite/ServiceWebsite/ClientApp/package.json
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/components/mic-visualiser/mic-visualiser.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/components/mic-visualiser/mic-visualiser.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/components/mic-visualiser/mic-visualiser.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-journey.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/models/config.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/config.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/config.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/EdgePF.js
ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/IEPF.js
ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/pexrtc.js
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-3942
Added audio bar component, script for pexip, add to config service pexip node to connect.
```
[ ] Yes
[ X] No
```

added audio visualizer, script for pexip, added in config pexip node

---

azure-pipelines.yml

Fixed Secret in Yml file
```
[X ] Yes
[ ] No
```

Fixed Secret in Yml file

---

azure-pipelines.yml

Fixed secrets in Yml file
```
[X ] Yes
[ ] No
```

Fixed Secrets in Yml file

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/models/user-media-device.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/models/user-media-device.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/services/user-media-stream.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/services/user-media-stream.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/testing/mocks/mock-logger.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.scss

https://tools.hmcts.net/jira/browse/VIH-3942
Added user media stream service
```
[ ] Yes
[X ] No
```

Added media stream service

---

azure-pipelines.yml

VIH-3942: Adding url endpoint

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/AboutYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/InternetConnection.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/PleaseContactUs.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/CheckYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/SwitchCameraMicrophone.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/ThankYou.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/YourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

n/a
Removed smoke test tags
```
[ ] Yes
[ ] No
```

Removed smoke test tags

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataSetUp.cs

n/a
Deletes all the stale records associated with the automation test accounts
```
[ ] Yes
[ x] No
```

Deletes all the stale records associated with the automation test accounts

---

ServiceWebsite/ServiceWebsite.Common/FakeHttpMessageHandler.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ControllerTestsBase.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ParticipantControllerTest.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/ServiceWebsite.IntegrationTests.csproj
ServiceWebsite/ServiceWebsite.Services/KinlyPlatformService.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/ParticipantControllerTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/FakeHttpMessageHandler.cs
ServiceWebsite/ServiceWebsite.UnitTests/Services/KinlyPlatformServiceTest.cs
ServiceWebsite/ServiceWebsite/ConfigureServicesExtensions.cs
ServiceWebsite/ServiceWebsite/Controllers/ConfigController.cs
ServiceWebsite/ServiceWebsite/Controllers/ParticipantController.cs

https://tools.hmcts.net/jira/browse/VIH-3942
```
[ ] Yes
[x ] No
```

Vih 3942 kinly tests

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/security/logout/logout.component.ts

https://tools.hmcts.net/jira/browse/VIH-4725
```
[ ] Yes
[x ] No
```

VIH-4725: Fixed model not being cleared on logout

---

ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ConfigControllerTests.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ControllerTestsBase.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ParticipantControllerTest.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/TokenControllerTests .cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Security/ServerHeaderTests.cs

n/a
Removed test tags to fix the build
```
[ ] Yes
[ x] No
```

Removed tags

---

ServiceWebsite/ServiceWebsite/Web.config

https://tools.hmcts.net/jira/browse/VIH-4846
include sub domains  for msecnd.net content security policy
```
[ ] Yes
[ X] No
```

allowed msecnd.net sub domain in content security policy

---

ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ControllerTestsBase.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ParticipantControllerTest.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/TokenControllerTests .cs
ServiceWebsite/ServiceWebsite.Services/KinlyPlatformService.cs
ServiceWebsite/ServiceWebsite/Controllers/ParticipantController.cs

Fix integration test
```
[ ] Yes
[ ] No
```

change integration test

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view-base/video-view-base.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/court-building-video/court-building-video.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/court-building-video/court-building-video.component.ts

https://tools.hmcts.net/jira/browse/VIH-4717
```
[ ] Yes
[x ] No
```

VIH-4717: Change methods to await and also mock out the child component Firefox

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey-routing.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual.gaurd.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual.gaurd.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey-routing.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative.gaurd.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative.gaurd.ts
ServiceWebsite/ServiceWebsite/ServiceWebsite.csproj

https://tools.hmcts.net/jira/browse/VIH-4619
Changes related to the bug 4619
```
[ ] Yes
[ X] No
```

Added Individual & Representative gaurds

---

ServiceWebsite/ServiceWebsite/ClientApp/package-lock.json
ServiceWebsite/ServiceWebsite/ClientApp/package.json
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/services/user-media-stream.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/services/user-media.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/main.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/polyfills.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/tsconfig.app.json
ServiceWebsite/ServiceWebsite/ClientApp/src/tsconfig.spec.json
ServiceWebsite/ServiceWebsite/ClientApp/src/typings.d.ts
ServiceWebsite/ServiceWebsite/ServiceWebsite.csproj
ServiceWebsite/ServiceWebsite/Web.config

WIP
WIP
```
[ ] Yes
[X ] No
```

add async to call pexip

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/journey-routing-listener.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/journey-routing-listener.service.ts

n/a
This fixes an issue of refreshing a page where ,currently, it takes the user back to the homepage
```
[ ] Yes
[x ] No
```

Fix for refresh of the any page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.ts

https://tools.hmcts.net/jira/browse/VIH-4866
Fix for the audio issue on Safari
```
[ ] Yes
[ x] No
```

Mute the audio when the video stops playing

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts

https://tools.hmcts.net/jira/browse/VIH-4954
Skip to main content
```
[ ] Yes
X] No
```

Skip to main content

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/mic-visualiser/mic-visualiser.component.ts

https://tools.hmcts.net/jira/browse/VIH-4881
Close audio context on Edge
```
[ ] Yes
[x ] No
```

Fixed audio issue on Edge

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/clients/api-client.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/profile.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/profile.service.ts
ServiceWebsite/ServiceWebsite/Controllers/ProfileController.cs
ServiceWebsite/ServiceWebsite/Models/UserProfileResponse.cs

https://tools.hmcts.net/jira/browse/VIH-4826
```
[ ] Yes
[ x] No
```

VIH-4826: redirect to unautorized page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.factory.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.factory.ts

https://tools.hmcts.net/jira/browse/VIH-4950
Representative journey should not start again if it was completed.
```
[ X] Yes
[ ] No
```

fix journey should not start again once it was completed.

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

https://tools.hmcts.net/jira/browse/VIH-4951
Fixes the issues caused by clicking the Replay button repeatedly
```
[ ] Yes
[ x] No
```

Replay video issue

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/footer/footer.component.html

https://tools.hmcts.net/jira/browse/VIH-4428
https://tools.hmcts.net/jira/browse/VIH-4427
```
[ ] Yes
[ x] No
```

VIH-4427_footer_links_same_tab

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/app-routing.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/scroll-trigger.directive.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/scroll-trigger.directive.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/window-scrolling.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/window-scrolling.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/footer/footer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/shared.module.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/paths.ts

https://tools.hmcts.net/jira/browse/VIH-4949
add accessibility page
```
[ X] Yes
[ ] No
```

added accessibility page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/scroll-trigger.directive.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/scroll-trigger.directive.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.html

VIH-4949
Layout for accessibility text
```
[ ] Yes
[X ] No
```

layout fix

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/questionnaire-completed/questionnaire-completed.component.html

https://tools.hmcts.net/jira/browse/VIH-4655
Questionnaire result questions shold be divided by bottom line
```
[ ] Yes
[ X] No
```

Divided line between questions in Questionnaire result page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/navigation-back-base.factory.ts

https://tools.hmcts.net/jira/browse/VIH-5024
```
[ ] Yes
[ ] No
```

VIH-5024: Fix when going back from first page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/user-camera-view/user-camera-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/user-camera-view/user-camera-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/use-camera-microphone/use-camera-microphone.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/user-media.service.ts

https://tools.hmcts.net/jira/browse/VIH-5029
Switch off camera after self video
```
[ X] Yes
[ ] No
```

Switch off camera after self video

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

https://tools.hmcts.net/jira/browse/VIH-5011
Catch errors block camera and show Blocked page
```
[ ] Yes
[X ] No
```

Catch error NotAllowedMedia and display Blocked msg

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/user-camera-view/user-camera-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view/video-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/user-media.service.ts

Fix issue related to FIX-5011
If the second video with self screen is blocked, no msg with erroris displayed, and screen is freezed.
```
[X ] Yes
[ ] No
```

Fix error block second video issue

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/SeleniumEnvironment.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/Browser.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/NuGet/Hooks/DataSetUp.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite/ClientApp/.gitignore

- Attempt to fix blocked cam errors on saucelabs
- Added package lock to gitignore
- Added a kill driver after test execution
- Added Geckodriver as a NuGet package
- Upgraded to latest version of test plugins
```
[ ] Yes
[X] No
```

Attempt to fix saucelabs

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/switch-on-camera-and-microphone/switch-on-camera-and-microphone.component.ts

N/a
Fixed automation issue that was causing all the tests to fail for media-blocked pages
```
[ ] Yes
[x ] No
```

Fixed automation issue for blocked camera issue

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/appointing-a-barrister/appointing-a-barrister.component.html

VIH-4995
Page title wording
```
[ ] Yes
[ X] No
```

page title

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/appointing-a-barrister/appointing-a-barrister.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.scss

VIH 4995, 4996
Position of back button
```
[ ] Yes
[X ] No
```

position of the back button

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-hearings/about-hearings.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/different-hearing-types/different-hearing-types.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-video-hearing/your-video-hearing.component.html

https://tools.hmcts.net/jira/browse/VIH-5097
Updates th colour on bluescreen upon tabbing on the buttons
```
[ ] Yes
[x ] No
```

Fixed insufficient colour contrast issue for Blue Screens

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/choice-textbox-form.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/page-tracker.service.ts

https://tools.hmcts.net/jira/browse/VIH-5092
```
[ ] Yes
[ ] No
```

VIH-5092: Adding focus to body and formcontrols

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/choice-textbox.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/choice-textbox.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.html

https://tools.hmcts.net/jira/browse/VIH-5117
Text changes
```
[ ] Yes
[ X] No
```

Button text changes

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/thank-you/thank-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/thank-you/thank-you.component.html

https://tools.hmcts.net/jira/browse/VIH-5118
https://tools.hmcts.net/jira/browse/VIH-5119
Wording changes on Thank you changes
```
[ ] Yes
[X ] No
```

Thank you page wording changes - Individual & Rep

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/journey-routing-listener.service.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/journey-routing-listener.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/participant-journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-your-computer/about-your-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-your-computer/about-your-computer.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-computer/your-computer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-computer/your-computer.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/services/journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/services/representative-journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/video-working/video-working.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/self-test-journey-component-bindings.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/app-insights-logger.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/console-logger.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/log-adapter.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/logger.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/logger.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/testing/mocks/mock-logger.ts

VIH-5068: adding telemetry to lookup in App Insights

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/thank-you/thank-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/thank-you/thank-you.component.html

https://tools.hmcts.net/jira/browse/VIH-5119
https://tools.hmcts.net/jira/browse/VIH-5118
Removed full stops
```
[ ] Yes
[X ] No
```

Removed Full Stops

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/video-view-base/video-view-component-test-bed.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-court-building/explore-court-building.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-court-building/explore-court-building.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-video-hearing/explore-video-hearing.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-video-hearing/explore-video-hearing.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.ts

https://tools.hmcts.net/jira/browse/VIH-5039
Refactoring, the second video doesn't show only self-view if the device is iPad or Mobile.
```
[X ] Yes
[ ] No
```

refactoring detect ipad

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/answers-saved/answers-saved.component.html

https://tools.hmcts.net/jira/browse/VIH-5182
Fix, a capital letter in 'Thank you' statement
```
[ ] Yes
[X ] No
```

answer saved page capital letter fix

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/accessibility/accessibility.component.html

VIH 4964
full stop missing
```
[ ] Yes
[X ] No
```

full stop missing

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/journey-routing-listener.service.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/individual-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-your-computer/about-your-computer.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-computer/your-computer.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/representative-journey.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

NOJIRA: Change telemetry string to include webapp name

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

https://tools.hmcts.net/jira/browse/VIH-5051
Collect telemetry for kinly score in self test
```
[ ] Yes
[ X] No
```

collect data for kinly score

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/contact-us/contact-us.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/show-details/show-details.component.html

https://tools.hmcts.net/jira/browse/VIH-5095
https://tools.hmcts.net/jira/browse/VIH-5096
Accessibility changes
```
[ ] Yes
[ X] No
```

Accessibility changes

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/switch-on-camera-and-microphone/switch-on-camera-and-microphone.component.html

https://tools.hmcts.net/jira/browse/VIH-5213
Changed wording on the page switch on camera and microphone
```
[X ] Yes
[ ] No
```

Change wording on switch on camera and mic

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/presenting-the-case/presenting-the-case.component.ts

https://tools.hmcts.net/jira/browse/VIH-523
Changed RegEx for email
```
[X ] Yes
[ ] No
```

Changed email RegEx

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/presenting-the-case/presenting-the-case.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/presenting-the-case/presenting-the-case.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/presenting-the-case/presenting-the-case.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/constants.ts

VIH-5231
Added validation to presenting case name input
```
[ X] Yes
[ ] No
```

add validation to presenting  case name

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/choice-textbox.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/components/choice-textbox.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-you/about-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-your-computer/about-your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/access-to-room/access-to-room.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/interpreter/interpreter.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-computer/your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-internet-connection/your-internet-connection.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/camera-working/camera-working.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/check-your-computer/check-your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/microphone-working/microphone-working.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/video-working/video-working.component.html

https://tools.hmcts.net/jira/browse/VIH-5123
Individual Journey - Error Message changes
```
[ ] Yes
[X ] No
```

Individual Journey - Error Message changes

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.html

https://tools.hmcts.net/jira/browse/VIH-5206
Rep Journey - Error Messages
```
[ ] Yes
[X ] No
```

Rep Journey - Error Messages

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/header/header.component.html

https://tools.hmcts.net/jira/browse/VIH-5354
Changed font size for header
```
[ X] Yes
[ ] No
```

Change font size for header to comply with the standard

---

ServiceWebsite/ServiceWebsite/Startup.cs

https://tools.hmcts.net/jira/browse/VIH-5197
Disabled swagger UI for production environment
```
[ X] Yes
[ ] No
```

Disabled Swagger UI for Production environment.

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/footer/footer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/footer/footer.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/footer/footer.component.ts

https://tools.hmcts.net/jira/browse/VIH-5223
Hide links in the footer for unsupported browsers
```
[ X] Yes
[ ] No
```

HIde links in footer for unsupported browsers

---

ServiceWebsite/ServiceWebsite.UnitTests/Services/ParticipantServiceTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Services/PollyRetryServiceTests.cs

VIH-5411: Adding unit tests for pollyRetryService

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

VIH-5420: Update the testcall1 to testcall2

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/header/header.component.html

https://tools.hmcts.net/jira/browse/VIH-5421
Changed sign out button to a link.
```
[ ] Yes
[x] No
```

VIH-5421:Service web | 'Sign out' link has turned into a button.

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-video-hearing/your-video-hearing.component.html

https://tools.hmcts.net/jira/browse/VIH-5474
Video Hearing information link
```
[ ] Yes
[x ] No
```

VIH-5474 - Video Hearing information link

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/device-type.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.ts

https://tools.hmcts.net/jira/browse/VIH-5501
Removed Edge from the list of unsupported browser list.
```
[ ] Yes
[x] No
```

Removed Edge from the list of unsupported browser list.

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Accessibility.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/YourInternetConnection.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/CheckYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/TestYourEquipment.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/VideoWorking.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/SuitabilityAnswerRequestBuilder.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/Representative/OtherInformationPage.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/Representative/OtherInformationSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/Representative/PresentingTheCaseSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/SelfTest/VideoWorkingSteps.cs
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

- Fixes for more tests
- Updated NuGet package
```
[ ] Yes
[X] No
```

Added fixes for more tests

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Accessibility.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/AnswersSavedIndividual.feature

- Added missing accessibility test for new page
```
[ ] Yes
[X] No
```

Added a test for accessibility

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/ErrorSteps.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/index.html

- Added fix for unsupported browser test
- Added ids in the Dom
```
[ ] Yes
[X] No
```

Added a fix for the unsupported browser test

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

- Added a smoketest for the redirect
- Added support for Edge and Edge Chronium to the NuGet package and updated the file on the project
```
[ ] Yes
[X] No
```

Added a smoketest and a support for Edge Chronium

---

ServiceWebsite/ServiceWebsite/ClientApp/angular.json
ServiceWebsite/ServiceWebsite/ClientApp/src/index.html
ServiceWebsite/ServiceWebsite/ClientApp/src/unsupported-browser.html

https://tools.hmcts.net/jira/browse/VIH-5525
attempt to fix the IE 11 redirect to login issue. 
moved the html content to a separate page.
added path to assets folder.
```
[ ] Yes
[x] No
```

moved the html to separate file for IE 11

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/CheckYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/SwitchOnCameraMicrophone.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

- 1 failed because of case sensitivity
- Another failed because the case details only appear for rep not individual
```
[ ] Yes
[X] No
```

Fixes for 2 broken tests

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

- FIx for IE unsupported browser sauelabs driver
```
[ ] Yes
[X] No
```

FIx for IE unsupported browser sauelabs driver

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/ErrorSteps.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.html

- Another attempt to fix unsupported browser tests
```
[ ] Yes
[X] No
```

Another attempt to fix the IE issue

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Configuration/Apis.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/HearingData.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/SuitabilityAnswerRequestBuilder.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/TestContext.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/ConfigHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HealthcheckHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HooksSequence.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RegisterApisHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/AnswersSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs

VIH-4858
- Added a test for a Rep who have previously completed the questionnaire
- Some more refactoring
- Moved more code to the NuGet package
```
[ ] Yes
[X] No
```

Added a test for Reps who have previously completed the questionnaire.

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-hearings/about-hearings.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-video-hearing/your-video-hearing.component.html

https://tools.hmcts.net/jira/browse/VIH-5519
Content changes for blue screens
```
[ ] Yes
[X ] No
```

VIH-5519-Content changes for blue screens

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/styles.css

https://tools.hmcts.net/jira/browse/VIH-5233
- added a role for the skip div.
- updated acceptance test nuget package to run on safari.
```
[ ] Yes
[x] No
```

VIH-5233: [Service Web | Accessibility] All pages should be contained within landmarks

---

.gitignore
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/ConfigHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/AnswersSteps.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

- Updated to run on Edge
```
[ ] Yes
[X] No
```

Updated test framework

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

- Updated the release name
```
[ ] Yes
[X] No
```

Upgraded NuGet package to update the overnight release name

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

- Upgraded to use latest Safaridriver
```
[ ] Yes
[X] No
```

Upgraded project to use latest Safaridriver

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/check-your-answers/check-your-answers.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/check-your-answers/check-your-answers.component.ts

https://tools.hmcts.net/jira/browse/VIH-5616
- updated text based on review feedback from content team/ test team.
```
[ ] Yes
[ ] No
```

VIH-5616-When the questionnaire pages load or when a user clicks on the screen a blue border on the page appears

---

CODEOWNERS
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/AnswersSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/BrowserSteps.cs
azure-pipelines.yml

- Javascript click has unexpected side effects for certain buttons on Firefox only. I have reverted this to the old WebDriver clicks now for Firefox only. 
```
[ ] Yes
[X] No
```

Switched the click method for firefox

---

ServiceWebsite/ServiceWebsite.UnitTests/.config/dotnet-tools.json
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/ParticipantControllerTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/TokenControllerTest.cs
ServiceWebsite/ServiceWebsite.UnitTests/stryker-config.json
ServiceWebsite/ServiceWebsite/Controllers/ParticipantController.cs

https://tools.hmcts.net/jira/browse/VIH-5540
- Added stryker mutation and settings file
- Updated unit test to resolve mutants
```
[ ] Yes
[x] No
```

Implement stryker mutation testing

---

.githooks/pre-commit
.githooks/prepare-commit-msg
README.md

https://tools.hmcts.net/jira/browse/VIH-5605
Added git hooks to validate branch name and commit messge
```
[ X] Yes
[ ] No
```

feature/VIH-5605 : added git hooks to validate branch name and commits

---

ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/pexrtc.js

https://tools.hmcts.net/jira/browse/VIH-5667
- updated the pexip.js to v23
```
[ ] Yes
[x] No
```

VIH-5667 : Regression_Test_Pexip_v.23

---

ServiceWebsite/ServiceWebsite.UnitTests/Controllers/ParticipantControllerTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/ProfileControllerTest.cs
ServiceWebsite/ServiceWebsite.UnitTests/Helper/ClaimsHelperTest.cs
ServiceWebsite/ServiceWebsite/Controllers/ParticipantController.cs
ServiceWebsite/ServiceWebsite/Controllers/ProfileController.cs
ServiceWebsite/ServiceWebsite/Helpers/ClaimsHelper.cs

https://tools.hmcts.net/jira/browse/VIH-5311
Resolve issues with unit test mutation and coverage, refactoring
```
[ ] Yes
[ ] No
```

feature/VIH-5311 : refactoring to kill unit test mutation and coverage

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/VerifyAnswersMatch.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

https://tools.hmcts.net/jira/browse/VIH-5713
Initialise self test score with None
```
[X ] Yes
[ ] No
```

feature/VIH-5713 : InitialiseSelftestScoreWithNone

---

.githooks/pre-commit
.githooks/prepare-commit-msg
ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/HearingData.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/TestData/DefaultDataManager.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/ConfigHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HealthcheckHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HooksSequence.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/AnswersSteps.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/HealthTests.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs
ServiceWebsite/ServiceWebsite/Controllers/HealthCheckController.cs

- Added a fix for the conferences for today updates
```
[ ] Yes
[X] No
```

VIH-5552 Added a fix for the conferences for today updates

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/device-type.ts

VIH-5575
- Make Edge Chromium supported
```
[ ] Yes
[X] No
```

VIH-5575 unblock edge chromium

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HooksSequence.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj

- Stop Edge Chromium server if running locally
```
[ ] Yes
[X] No
```

VIH-5255  Stop Edge Chromium server if running locally

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/ParticipantRequestBuilder.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/useraccounts.json
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs

VIH-5383
-Solicitor request changes in bookings api
```
[ ] Yes
[X] No
```

VIH-5383 Solicitor request changes in bookings api

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/TestContext.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HooksSequence.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

-Handle sauce labs time zone issues
```
[ ] Yes
[X] No
```

VIH-5255 Handle sauce labs time zone issues

---

ServiceWebsite/ServiceWebsite.UnitTests/Controllers/HealthTests.cs
ServiceWebsite/ServiceWebsite/Controllers/HealthCheckController.cs
ServiceWebsite/ServiceWebsite/Models/HealthCheckResponse.cs

…oved the video api health check.
vih-5629
removed video api health check, 
```
[ ] Yes
[x] No
```

VIH-5629 Add version property to healthcheck endpoint

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/mic-visualiser/mic-visualiser.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/testing/stubs/mic-visualiser-stub.ts

https://tools.hmcts.net/jira/browse/VIH-5889
Fix moving sound bar
```
[X ] Yes
[ ] No
```

VIH-5889 fix moving sound bar

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/AnswersSavedIndividual.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/ThankYou.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Representative/AnswersSavedRepresentative.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Representative/ThankYouRep.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/SignBackIn.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/TestYourEquipment.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/BrowserSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/SelfTest/TestYourEquipmentSteps.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ControllerTestsBase.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-5856
- Added tagging for extended smoketest for beta pipeline
```
[ ] Yes
[X] No
```

VIH-5856 extended smoketest

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/beta-banner/beta-banner.component.html

https://tools.hmcts.net/jira/browse/VIH-5934
- updated html to open feedback link in same tab
```
[ ] Yes
[x] No
```

VIH-5934 Accessibility_Feedback_link_should_open_up_in_the_same tab

---

README.md

https://tools.hmcts.net/jira/browse/VIH-6086
- Updated readme instructions with Stryker run
```
[ ] Yes
[x] No
```

VIH-6086 Updated readme instructions with Stryker run

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/user-camera-view/user-camera-view.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/components/user-camera-view/user-camera-view.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.ts

https://tools.hmcts.net/jira/browse/VIH-5984
mirror view for self video
```
[X ] Yes
[ ] No
```

VIH-5984 mirror view for self video

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

- Fix for driver creation on Sauce Labs for the overnights
```
[ ] Yes
[X] No
```

VIH-5255 Fix for devices

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Updated package lock
```
[ ] Yes
[X] No
```

VIH-5255 Update package lock

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Fix for build name
```
[ ] Yes
[X] No
```

VIH-5255 Build name fix

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/DateFormats.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Fix for date time issue on preprod
```
[ ] Yes
[X] No
```

VIH-5255 Hotfix for Preprod datetime issue

---

ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/pexrtc.js

https://tools.hmcts.net/jira/browse/VIH-6130
- updated js to version on https://sip.test.hearings.hmcts.net/static/webrtc/js/pexrtc.js
```
[ ] Yes
[x] No
```

VIH-6130 Update_to_Pexip_version_23.4

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/DateFormats.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/BrowserSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
azure-pipelines.nightly.yml

- Reschedule nightly jobs
```
[ ] Yes
[X] No
```

VIH-5255 Reschedule nightly jobs

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/DateFormats.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

- Disabled logging for Windows Firefox tests
- Fixed a date time issue for Edge Chromium
```
[ ] Yes
[X] No
```

VIH-5255 Disable logging for Windows Firefox

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Add retry mechanism for browser launch
```
[ ] Yes
[X] No
```

VIH-5255 Retry mechanism

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Removed retry but moved from wrapped driver to NgDriver
```
[ ] Yes
[X] No
```

VIH-5255 Removed retry and moved launch browser to NgDriver

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
azure-pipelines.beta.yml

- Fix for Beta Build
```
[ ] Yes
[X] No
```

VIH-5255 Fix for Beta Build

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Fix for BrowserVersion
```
[ ] Yes
[X] No
```

VIH-5255 Fix for BrowserVersion

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/directives/scroll-trigger.directive.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/participant-view/participant-view.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/check-your-answers/check-your-answers.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/other-information/other-information.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/your-video-hearing/your-video-hearing.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/test-your-equipment/test-your-equipment.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/services/user-media-stream.service.spec.ts

https://tools.hmcts.net/jira/browse/VIH-6248
Update content for representative journey
```
[ ] Yes
[ ] No
```

VIH-6248 update content for represenative

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/AboutYou.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/Consent.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/YourComputer.feature
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-hearings/about-hearings.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/about-you/about-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/different-hearing-types/different-hearing-types.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/explore-court-building/explore-court-building.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/help-the-court-decide/help-the-court-decide.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/thank-you/thank-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-computer/your-computer.component.html

https://tools.hmcts.net/jira/browse/VIH-6247
Content updates for Individual BTD journey
```
[ ] Yes
[x ] No
```

VIH-6247 Content changes

---

CODEOWNERS
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Representative/OtherInformation.feature

https://tools.hmcts.net/jira/browse/VIH-6248
- Content change fix
- Changed code owners to VH 
```
[ ] Yes
[X] No
```

VIH-6248 Content changes fix

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/thank-you/thank-you.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/your-computer/your-computer.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/date-time.pipe.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/shared/date-time.pipe.ts

https://tools.hmcts.net/jira/browse/VIH-6247
Content and datetime fix
```
[ ] Yes
[ x] No
```

VIH-6247 Content and datetime fix

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/privacy-policy/privacy-policy.component.html

https://tools.hmcts.net/jira/browse/VIH-6114
- amended text
```
[ ] Yes
[x] No
```

VIH-6114 Amend_Privacy_Policy_wording_to_include_audio

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/individual-journey/pages/consent/consent.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/privacy-policy/privacy-policy.component.html

https://tools.hmcts.net/jira/browse/VIH-6114
- updated text in other sections
```
[ ] Yes
[x] No
```

VIH-6114 amend privacy policy wording to include audio

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/check-your-answers/check-your-answers.component.css
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/representative-journey/pages/check-your-answers/check-your-answers.component.html

VIH-6370
Replace table with div and css
```
[ X] Yes
[ ] No
```

VIH-6370 replace table css

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml
azure-pipelines.yml

VIH-6286
add support across all pipelines for better FW await
```
[ ] Yes
[x] No
```

VIH-6286 add support across all pipelines for better FW await

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/Representative/CheckYourAnswersSteps.cs

- Fix for 2 failing tests overnight
```
[ ] Yes
[X] No
```

VIH-5255 Fix for 2 overnight failing tests

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.UserAPI.Client/UserApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs
azure-pipelines.nightly.yml

https://tools.hmcts.net/jira/browse/VIH-6269
- Fixes for overnight failing tests
```
[ ] Yes
[X] No
```

VIH-6269 Fix overnight issues

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/LoginSteps.cs

- Increase retries for Safari re login
```
[ ] Yes
[X] No
```

VIH-5255 Increase retries for Safari re login

---

ServiceWebsite/ServiceWebsite/ClientApp/angular.json
ServiceWebsite/ServiceWebsite/ClientApp/package-lock.json
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/SupportedBrowserModel.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.html
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.ts

https://tools.hmcts.net/jira/browse/VIH-6139
- updated page to include ipad.
```
[ ] Yes
[x] No
```

VIH-6139 Add_Ipad-Safari_to_supported_browser_page

---

CODEOWNERS
ServiceWebsite/ServiceWebsite.AcceptanceTests/Properties/AssemblyInfo.cs
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-6545
- Enable parallel test execution
```
[ ] Yes
[X] No
```

VIH-6545 Enable parallel test execution

---

ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/pexrtc.js

VIH-6433
update pexip client
```
[ ] Yes
[x] No
```

VIH-6433 update pexip client

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml
azure-pipelines.yml

VIH-6594
Update pipeline endpoints
```
[ ] Yes
[x] No
```

VIH-6594 Update pipeline endpoints

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/BrowserSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

- Fix for static method issue on parallel executions
```
[ ] Yes
[X] No
```

VIH-5255 Fix for static method issue on parallel executions

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Accessibility.feature

- https://tools.hmcts.net/jira/browse/VIH-6442
- Some pages removed where the accessibility test remained
```
[ ] Yes
[X] No
```

VIH-6442 Remove Pages from Accessibility tests

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/switch-on-camera-and-microphone/switch-on-camera-and-microphone.component.html

https://tools.hmcts.net/jira/browse/VIH-6442

VIH-6442 Adding 1 word to indv journey

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

- Daylight Saving Fix
```
[ ] Yes
[X] No
```

VIH-5255 Daylight Saving Fix

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/CheckYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/SignBackIn.feature

https://tools.hmcts.net/jira/browse/VIH-6380
- Remove saved answers functionality from single page
```
[ ] Yes
[X] No
```

VIH-6380 Remove saved answers functionality from single page

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Errors.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/HeaderFooter.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/SelfTest/CheckYourComputer.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/Page.cs

- More fixes for removed pages
```
[ ] Yes
[X] No
```

VIH-5255 More fixes for removed pages

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs

- Updated Test Api Client and packages
```
[ ] Yes
[X] No
```

VIH-6690 Updated Test Api Client and packages

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/AnswersSteps.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

VIH-6620
Fix for acceptance test, check on null answers ( in case no answers)
```
[ ] Yes
[ ] No
```

VIH-6620 fix for acceptance  test no answers

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/self-test-journey/pages/sign-back-in/sign-back-in.component.html

https://tools.hmcts.net/jira/browse/VIH-6812
Changed content of the sign back page
```
[ X] Yes
[ ] No
```

VIH-6812 change content of the sign back page

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/HearingData.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/HearingRequestBuilder.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/Users.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.UnitTests/.config/dotnet-tools.json
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-6768
test for PM and Winger should be redirected to video-web
```
[ X] Yes
[ ] No
```

VIH-6768 add test PM and Winger redirected to video web

---

ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts

https://tools.hmcts.net/jira/browse/VIH-6894

VIH-6894 Allow none user role

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DriverHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/HooksSequence.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs
ServiceWebsite/ServiceWebsite/ClientApp/package-lock.json

https://tools.hmcts.net/jira/browse/VIH-7061
- refactoring the driver hooks for local parallel execution
```
[ ] Yes
[X] No
```

VIH-7061 refactoring driver hooks for local parallel execution

---

ServiceWebsite/NuGet.Config
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/ConfigHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/appsettings.json
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.AcceptanceTests/parameters.runsettings
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-7058
- Add ability to switch local test environment execution
- Add ability to run from local to Sauce Labs
```
[ ] Yes
[X] No
```

VIH-7058 Add Local Environment Switching

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/DataHooks.cs

https://tools.hmcts.net/jira/browse/VIH-7059
- remove parallel execution workaround
```
[ ] Yes
[X] No
```

VIH-7059 Remove parallel execution workaround

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Data/HearingRequestBuilder.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Helpers/Users.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/RemoveDataHooks.cs
ServiceWebsite/ServiceWebsite.BookingApi.Client/BookingsApiClient.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ConfigControllerTests.cs
ServiceWebsite/ServiceWebsite.IntegrationTests/Controller/ControllerTestsBase.cs
ServiceWebsite/ServiceWebsite.TestAPI.Client/TestApiClient.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/HearingSuitabilityControllerTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/HearingsControllerTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/ParticipantControllerTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/TestIdentity.cs
ServiceWebsite/ServiceWebsite.UnitTests/Controllers/TokenControllerTest.cs
ServiceWebsite/ServiceWebsite.UnitTests/HashGeneratorTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/HearingServiceTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Services/HearingSuitabilityServiceTests.cs
ServiceWebsite/ServiceWebsite.UnitTests/Services/ParticipantServiceTests.cs
ServiceWebsite/ServiceWebsite.UserAPI.Client/UserApiClient.cs
ServiceWebsite/ServiceWebsite.VideoAPI.Client/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-7309
Update emails and Case Type Generic
```
[ ] Yes
[X] No
```

VIH-7309 Update emails and Case Type Generic

---

ServiceWebsite/ServiceWebsite.IntegrationTests/packages.lock.json
ServiceWebsite/ServiceWebsite.UnitTests/packages.lock.json
ServiceWebsite/ServiceWebsite/Program.cs
ServiceWebsite/ServiceWebsite/ServiceWebsite.csproj
ServiceWebsite/ServiceWebsite/packages.lock.json

VIH-7409
load aks configuration
```
[ ] Yes
[X] No
```

VIH-7409 load aks configuration

---

ServiceWebsite/ServiceWebsite/ConfigureServicesExtensions.cs

https://tools.hmcts.net/jira/browse/VIH-7451
- redirect fix.
```
[ ] Yes
[x] No
```

VIH-7451 Service_web_URL_is_rerouting_directly_to_video_web

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/Page.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json
ServiceWebsite/ServiceWebsite.Common/ServiceWebsite.Common.csproj
ServiceWebsite/ServiceWebsite.IntegrationTests/ServiceWebsite.IntegrationTests.csproj
ServiceWebsite/ServiceWebsite.IntegrationTests/packages.lock.json
ServiceWebsite/ServiceWebsite.Services/ServiceWebsite.Services.csproj
ServiceWebsite/ServiceWebsite.UnitTests/ServiceWebsite.UnitTests.csproj
ServiceWebsite/ServiceWebsite.UnitTests/packages.lock.json
ServiceWebsite/ServiceWebsite/ServiceWebsite.csproj
ServiceWebsite/ServiceWebsite/packages.lock.json

Fix smoke test skip issue
```
[ ] Yes
[X] No
```

VIH-5552 Fix smoke test skip issue

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

- Update to TextOf
```
[ ] Yes
[X] No
```

VIH-5552 Update to TextOf

---

ServiceWebsite/ServiceWebsite/web.config

https://tools.hmcts.net/jira/browse/VIH-7135
Remove HTTP Headers
```
[ ] Yes
[x] No
```

VIH-7135 Verbose-HTTP-Headers Web.Config

---

azure-pipelines.release.yml

https://tools.hmcts.net/jira/browse/VIH-6831
Added a new parameter to be passed to the release pipeline that holds the upper env url
```
[ ] Yes
[X] No
```

VIH-6831 Automate Vanity URLs

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.ts

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/VIH-7913
Change description
Remove IE from unsupported browsers
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

VIH-7913 remove-IE-from-unsupported-browsers-page

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.html

https://tools.hmcts.net/jira/browse/VIH-7977
Update content for unsupported web page
```
[ ] Yes
[x] No
```

VIH-7977 Update wording for Unsupported browsers page

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

VIH-7990 - Chromedriver update

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/CommonSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/appsettings.json
ServiceWebsite/ServiceWebsite/appsettings.json

VIH-8053
Added a wait before clicking a button, the click would happen too early before the page had loaded.
```
[ ] Yes
[ X] No
```

VIH-8053 - add a wait for the login page.

---

ServiceWebsite/ServiceWebsite/ClientApp/src/.browserslistrc
ServiceWebsite/ServiceWebsite/ClientApp/tsconfig.json

https://tools.hmcts.net/jira/browse/VIH-8050
Browserlistrc and tsconfig.json update to use IE
```
[ ] Yes
[X] No
```

VIH-8050 IE Unsupported-browser page not properly redirecting

---

ServiceWebsite/ServiceWebsite/ClientApp/src/.browserslistrc
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/tsconfig.json

https://tools.hmcts.net/jira/browse/VIH-8050
app.component update to use async subcribe event and using checkbrowser after post auth event
```
[ ] Yes
[X] No
```

VIH-8050 unsupported browser page not properly redirecting

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml

https://tools.hmcts.net/jira/browse/VIH-8088
Added Ejud config setting
```
[ ] Yes
[ ] No
```

VIH-8088 - Added Ejud config setting

---

azure-pipelines.beta.yml
azure-pipelines.nightly.yml
azure-pipelines.release.yml

https://tools.hmcts.net/jira/browse/VIH-8088
```
[ ] Yes
[ ] No
```

VIH-8088 removal of UsingEjud setting in Service Web yml files

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/unsupported-browser/unsupported-browser.component.html

https://tools.hmcts.net/jira/browse/VIH-8014
- Removed unused translation.
- Updated required wording.
```
[ ] Yes
[x] No
```

VIH-8014 Update wording for unsupported browsers page

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

VIH-8030 update to latest Acceptance Test Project

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/browser.constants.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/device-type.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/modules/base-journey/services/device-type.ts

https://tools.hmcts.net/jira/browse/VIH-8141
- added samsung as supported browser
```
[ ] Yes
[x] No
```

VIH-8141 added constants for browser names, added samsung as supported browser

---

ServiceWebsite/ServiceWebsite/ClientApp/src/scripts/pexrtc.js

https://tools.hmcts.net/jira/browse/VIH-7885
- Updated Pexip version
```
[x] Yes
[ ] No
```

VIH-7885 Upgrade pexip version to 25.4

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/app.component.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/home/home.component.spec.ts
ServiceWebsite/ServiceWebsite/ClientApp/src/app/pages/home/home.component.ts

https://tools.hmcts.net/jira/browse/VIH-8144
- unsubscribed from event service when component using the service is destroyed
```
[ ] Yes
[x] No
```

VIH-8144 unsubscribing from event service when component using it gets destroyed

---

ServiceWebsite/ServiceWebsite/ClientApp/src/app/services/app-insights-logger.service.ts

https://tools.hmcts.net/jira/browse/VIH-8144
- app insights not initialized causing error page it be shown
```
[ ] Yes
[x] No
```

VIH-8144 added null check for app insights instance

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-8053
added a fornightly run to the CI pipeline to ensure there is always a app artefact available
```
[ ] Yes
[X] No
```

VIH-8053 fortnightly ci run

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Configuration/ServiceWebConfig.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Login.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Hooks/ConfigHooks.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/Page.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/ServiceWebsite.AcceptanceTests.csproj
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/LoginSteps.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/appsettings.json
ServiceWebsite/ServiceWebsite.AcceptanceTests/packages.lock.json

logout script changes
https://tools.hmcts.net/jira/browse/VIH-7953
```
[ ] Yes
[ ] No
```

VIH-7953 logout script changes

---

ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Individual/ThankYou.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Features/Representative/ThankYouRep.feature
ServiceWebsite/ServiceWebsite.AcceptanceTests/Pages/CommonServiceWebPage.cs
ServiceWebsite/ServiceWebsite.AcceptanceTests/Steps/BrowserSteps.cs

https://tools.hmcts.net/jira/browse/VIH-8651
Some error handling in order to print out 'no hearing message' in the logs
```
[ ] Yes
[ ] No
```

VIH-8651 fixes after pipeline config issue
